import { MovementPhase, PoseData, ExerciseState, RepStats, AttemptLogEntry } from './types';
import { StandingCalfRaiseRule } from './StandingCalfRaiseRule';
import { PlieSquatRule } from './PlieSquatRule';
import { SquatRule } from './SquatRule';
import { SplitLungeRule } from './SplitLungeRule';

export interface IExerciseRule {
  validate(pose: PoseData, state: ExerciseState): {
    newPhase: MovementPhase;
    feedback: string[];
    isRepCompleted: boolean;
    isMovementFinished: boolean;
    qualityScore: number;
    angles: Record<string, number>;
    newAttempt?: AttemptLogEntry;
  };
  setRules(rules: any[]): void;
}

export class MovementEngine {
  private state: ExerciseState;
  private rule: IExerciseRule;
  private currentRepMetadata: Partial<RepStats> & { frameCount: number } | null = null;
  private lastMovementStats: RepStats | null = null;
  private minRepDurationSeconds: number = 0.8;

  constructor(exerciseName: string = 'Standing Calf Raise', rules?: any[]) {
    this.state = {
      currentPhase: MovementPhase.INITIALIZING,
      repCount: 0,
      attemptCount: 0,
      feedback: [],
      accuracyScore: 100,
      lastRepQuality: 0,
      isStarted: false,
      attemptLog: [],
    };

    this.rule = new StandingCalfRaiseRule(); // Default
    this.setExercise(exerciseName);

    if (rules && rules.length > 0) {
      this.setRules(rules);
    }
  }

  public setExercise(exerciseName: string) {
    console.log('Engine switching to:', exerciseName);
    const name = exerciseName.toLowerCase();
    
    if (name.includes('plie') || name.includes('pile')) {
      this.rule = new PlieSquatRule();
    } else if (name.includes('squat') && !name.includes('split')) {
      this.rule = new SquatRule();
    } else if (name.includes('lunge') || name.includes('split')) {
      this.rule = new SplitLungeRule();
    } else {
      this.rule = new StandingCalfRaiseRule();
    }
    this.state.currentPhase = MovementPhase.INITIALIZING;
  }

  public setRules(rules: any[]) {
    this.rule.setRules(rules);
    
    // Extract movement engine specific rules
    const tempoRule = rules.find(r => r.rule_name === 'TEMPO_STILLNESS');
    if (tempoRule?.threshold_value?.min_duration_sec) {
      this.minRepDurationSeconds = tempoRule.threshold_value.min_duration_sec;
      console.log('Engine Min Duration Updated:', this.minRepDurationSeconds);
    }
  }

  public start() {
    this.state.isStarted = true;
    this.state.startTime = Date.now();
    this.state.currentPhase = MovementPhase.START_POSITION;
    this.state.repCount = 0;
    this.state.accuracyScore = 100;
    this.state.lastRepQuality = 0;
    this.state.attemptCount = 0;
    this.state.attemptLog = [];
    this.resetRepMetadata();
  }

  private resetRepMetadata() {
    this.currentRepMetadata = {
      repNumber: this.state.repCount + 1,
      startTime: new Date().toISOString(),
      deviations: [],
      startFrameLandmarks: {},
      endFrameLandmarks: {},
      startFrameAngles: {},
      endFrameAngles: {},
      frameCount: 0,
      _descendingFramesBuffer: [],
      _ascendingFramesBuffer: []
    };
  }

  public stop() {
    this.state.isStarted = false;
    this.state.feedback = [];
    this.state.currentPhase = MovementPhase.INITIALIZING;
  }

  public processFrame(pose: PoseData): ExerciseState {
    if (!this.state.isStarted) return this.state;

    // Debugging: Log active rule once every 100 frames to avoid spam
    if (this.currentRepMetadata && this.currentRepMetadata.frameCount % 100 === 0) {
      console.log('Active Engine Rule:', this.rule.constructor.name, 'Phase:', this.state.currentPhase);
    }

    const result = this.rule.validate(pose, this.state);
    
    // Log any new attempts generated by the rule with a 1-second debounce
    if (result.newAttempt) {
      const now = Date.now();
      const lastAttempt = this.state.attemptLog[0];
      const timeSinceLast = lastAttempt ? now - lastAttempt.timestamp : 1001;

      if (timeSinceLast > 1000) { // 1-second debounce
        this.state.attemptCount++;
        this.state.attemptLog = [result.newAttempt, ...this.state.attemptLog].slice(0, 500);
      }
    }

    if (this.currentRepMetadata) {
      this.currentRepMetadata.frameCount++;
      
      // Handle Start of Rep Detection based on Phase changes
      const isStartingRep = 
        (this.state.currentPhase === MovementPhase.START_POSITION && 
         (result.newPhase === MovementPhase.HEEL_RAISE || result.newPhase === MovementPhase.DESCENDING));

      if (isStartingRep) {
        this.currentRepMetadata.startFrameLandmarks = { ...pose };
        this.currentRepMetadata.startFrameAngles = { ...result.angles };
      }
      if (result.newPhase === MovementPhase.DESCENDING || result.newPhase === MovementPhase.LOWERING) {
        this.currentRepMetadata._descendingFramesBuffer?.push({ pose: { ...pose }, angles: { ...result.angles } });
      } else if (result.newPhase === MovementPhase.ASCENDING) {
        this.currentRepMetadata._ascendingFramesBuffer?.push({ pose: { ...pose }, angles: { ...result.angles } });
      }
      
      if (result.newPhase !== this.state.currentPhase) {
        // Extract intermediate frames if we just finished a motion phase
        if (this.state.currentPhase === MovementPhase.DESCENDING || this.state.currentPhase === MovementPhase.LOWERING) {
          const buf = this.currentRepMetadata._descendingFramesBuffer || [];
          if (buf.length > 0) {
            const idx1 = Math.floor(buf.length * 0.33);
            const idx2 = Math.floor(buf.length * 0.66);
            this.currentRepMetadata.descendingFrame1Landmarks = buf[idx1].pose;
            this.currentRepMetadata.descendingFrame1Angles = buf[idx1].angles;
            this.currentRepMetadata.descendingFrame2Landmarks = buf[idx2].pose;
            this.currentRepMetadata.descendingFrame2Angles = buf[idx2].angles;
            this.currentRepMetadata._descendingFramesBuffer = []; // Free memory
          }
        }
        
        if (this.state.currentPhase === MovementPhase.ASCENDING) {
          const buf = this.currentRepMetadata._ascendingFramesBuffer || [];
          if (buf.length > 0) {
            const idx1 = Math.floor(buf.length * 0.33);
            const idx2 = Math.floor(buf.length * 0.66);
            this.currentRepMetadata.ascendingFrame1Landmarks = buf[idx1].pose;
            this.currentRepMetadata.ascendingFrame1Angles = buf[idx1].angles;
            this.currentRepMetadata.ascendingFrame2Landmarks = buf[idx2].pose;
            this.currentRepMetadata.ascendingFrame2Angles = buf[idx2].angles;
            this.currentRepMetadata._ascendingFramesBuffer = []; // Free memory
          }
        }

        // Handle Peak/Top Detection
        if (result.newPhase === MovementPhase.TOP_POSITION || result.newPhase === MovementPhase.BOTTOM_POSITION) {
          this.currentRepMetadata.topTime = new Date().toISOString();
          this.currentRepMetadata.topFrameLandmarks = { ...pose };
          this.currentRepMetadata.topFrameAngles = { ...result.angles };
        } else if ((result.newPhase === MovementPhase.LOWERING || result.newPhase === MovementPhase.ASCENDING) && !this.currentRepMetadata.topFrameLandmarks) {
          this.currentRepMetadata.topTime = new Date().toISOString();
          this.currentRepMetadata.topFrameLandmarks = { ...pose };
          this.currentRepMetadata.topFrameAngles = { ...result.angles };
        }
        this.state.currentPhase = result.newPhase;
      } else if (this.currentRepMetadata.topFrameLandmarks) {
        // Continuous Peak Tracking: update the peak if they go deeper/higher while still in the phase
        if (result.newPhase === MovementPhase.BOTTOM_POSITION) {
          // In squats/lunges, hips go down (Y increases). Higher Y = deeper.
          const currentHipsY = (pose['LEFT_HIP']?.y || 0) + (pose['RIGHT_HIP']?.y || 0);
          const bestHipsY = (this.currentRepMetadata.topFrameLandmarks['LEFT_HIP']?.y || 0) + (this.currentRepMetadata.topFrameLandmarks['RIGHT_HIP']?.y || 0);
          
          if (currentHipsY > bestHipsY) {
            this.currentRepMetadata.topTime = new Date().toISOString();
            this.currentRepMetadata.topFrameLandmarks = { ...pose };
            this.currentRepMetadata.topFrameAngles = { ...result.angles };
          }
        } else if (result.newPhase === MovementPhase.TOP_POSITION) {
          // In calf raises, heels go up (Y decreases). Lower Y = higher.
          const currentHeelsY = (pose['LEFT_HEEL']?.y || 0) + (pose['RIGHT_HEEL']?.y || 0);
          const bestHeelsY = (this.currentRepMetadata.topFrameLandmarks['LEFT_HEEL']?.y || 0) + (this.currentRepMetadata.topFrameLandmarks['RIGHT_HEEL']?.y || 0);
          
          if (currentHeelsY < bestHeelsY) {
            this.currentRepMetadata.topTime = new Date().toISOString();
            this.currentRepMetadata.topFrameLandmarks = { ...pose };
            this.currentRepMetadata.topFrameAngles = { ...result.angles };
          }
        }
      }

      if (result.feedback.length > 0) {
        result.feedback.forEach(msg => {
          const alreadyLogged = this.currentRepMetadata?.deviations?.some(d => d.message === msg);
          if (!alreadyLogged && this.currentRepMetadata?.deviations) {
            this.currentRepMetadata.deviations.push({
              type: 'posture',
              message: msg,
              severity: 'warning',
              frameNumber: this.currentRepMetadata.frameCount || 0
            });
          }
        });
      }
    }

    this.state.currentPhase = result.newPhase;
    this.state.feedback = result.feedback;

    if (result.isMovementFinished && this.currentRepMetadata) {
      const endTime = new Date().toISOString();
      const startTimeDate = new Date(this.currentRepMetadata.startTime!);
      const endTimeDate = new Date(endTime);
      const duration = (endTimeDate.getTime() - startTimeDate.getTime()) / 1000;

      // Prepare stats for this movement regardless of outcome
      this.lastMovementStats = {
        ...this.currentRepMetadata as RepStats,
        endTime: endTime,
        qualityScore: result.qualityScore,
        durationSeconds: duration,
        status: result.isRepCompleted ? 'valid' : 'failed',
        endFrameLandmarks: { ...pose },
        endFrameAngles: { ...result.angles }
      };

      if (result.isRepCompleted) {
        // Strict Duration Check for successful reps
        if (duration < this.minRepDurationSeconds) {
          this.resetRepMetadata();
          this.state.currentPhase = MovementPhase.START_POSITION;
          return { ...this.state };
        }

        this.state.repCount++;
        this.state.lastRepQuality = 100;
      }

      this.resetRepMetadata();
      this.state.currentPhase = MovementPhase.START_POSITION;
    }

    this.state.accuracyScore = this.state.attemptCount > 0 
      ? (this.state.repCount / this.state.attemptCount) * 100
      : 100;

    return { ...this.state };
  }

  public getState(): ExerciseState {
    return { ...this.state };
  }

  public getLastMovementStats(): RepStats | null {
    return this.lastMovementStats;
  }
}
